[INQUISITOR]
id = "001"
eco = "Other"
url = "https://github.com/B1NARY-GR0UP/inquisitor"
level = "III"

[PIANO]
id = "002"
eco = "BINARY WEB ECOLOGY"
url = "https://github.com/B1NARY-GR0UP/piano"
level = "II"

[DREAMEMO]
id = "003"
eco = "BINARY WEB ECOLOGY"
url = "https://github.com/B1NARY-GR0UP/dreamemo"
level = "III"

[PHOS]
id = "004"
eco = "Basic Middleware Service"
url = "https://github.com/B1NARY-GR0UP/phos"
level = "II"

[VIOLIN]
id = "005"
eco = "Basic Middleware Service"
url = "https://github.com/B1NARY-GR0UP/violin"
level = "II"

[NWA]
id = "006"
eco = "Basic Middleware Service"
url = "https://github.com/B1NARY-GR0UP/nwa"
level = "I"

[GHS]
id = "007"
eco = "Make Your Life Simpler"
url = "https://github.com/B1NARY-GR0UP/ghs"
level = "II"

[TABSNAPSHOT]
id = "008"
eco = "Make Your Life Simpler"
url = "https://github.com/B1NARY-GR0UP/tabsnapshot"
level = "II"

[OPENALYSIS]
id = "009"
eco = "BINARY WEB ECOLOGY"
url = "https://github.com/B1NARY-GR0UP/openalysis"
level = "I"

[RAFT]
id = "010"
eco = "PROJECT: FOIVER"
url = "https://github.com/B1NARY-GR0UP/raft"
level = "I"

[ORIGINIUM]
id = "011"
eco = "PROJECT: FOIVER"
url = "https://github.com/B1NARY-GR0UP/originium"
level = "I"
