[INQUISITOR]
id = ""
url = ""
desc = ""
level = ""
status = ""
keywords = ["", ""]

[PIANO]
id = ""
url = ""
desc = ""
level = ""
status = ""
keywords = ["", ""]

[DREAMEMO]
id = ""
url = ""
desc = ""
level = ""
status = ""
keywords = ["", ""]

[PHOS]
id = ""
url = ""
desc = ""
level = ""
status = ""
keywords = ["", ""]

[VIOLIN]
id = ""
level = ""
url = ""
desc = ""
keywords = ["", ""]
status = ""